### PR TITLE
fix(title): encode html tags

### LINKED ISSUE #23: Title isn't html encoded
As seen here:

https://github.com/algolia/github-helpscout-collector/blob/e23d9f72fcfbd2fec28298ef436ea3ee53cb4933/src/service.ts#L82

The title is verbatim sent from GitHub. If this title has something like a JSX tag, I'm suspecting that help scout filters out any html tag. We instead should encode it. I assume it should be html encoding (`%lt;`), but it could be different too.

Alternatively we can strip the html brackets but keep the contents. That way some context is lost, but the main tag is still in the title.

I've only seen this issue two times so far, so it's pretty low priority for me.

### PR DESCRIPTION
**Pull request by Haroenv**
I don't know for sure if this will show up correctly on Helpscout, but from reading their API docs this should be correct.

fixes #23

### CODE REVIEW

File: src/service.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ import { mount } from './database';
 import { findMailboxId } from './findMailboxId';
 import { createHelpScoutClient } from './helpScoutClient';
 import { formatText } from './helpScoutTemplate';
+import {encodeHtml} from './htmlEntities'
```
Comment (Haroenv) [inline src/service.ts]:
```suggestion
import { encodeHtml } from './htmlEntities';
```

prettier without eslint makes you lazy

File: src/htmlEntities.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+const entities: { [key: string]: string } = {
+  '<': '&lt;',
+  '>': '&gt;',
+};
+
+export const encodeHtml = (str: string) => str.replace(/[&<>'"]/g, tag => entities[tag] || tag);
```
Comment (samouss) [inline src/htmlEntities.ts]: Why do we have to use `&,',"` if we return them?

Comment (Haroenv) [reply src/htmlEntities.ts]: I modified another script to make it simpler since we don't care about those other characters, but forgot to modify the regex, will fix

Comment (Haroenv) [reply src/htmlEntities.ts]: I modified another script to make it simpler since we don't care about those other characters, but forgot to modify the regex, will fix

Comment (Haroenv) [reply src/htmlEntities.ts]:
```suggestion
export const encodeHtml = (str: string) => str.replace(/[<>]/g, tag => entities[tag] || tag);
```

Comment (Haroenv) [reply src/htmlEntities.ts]:
```suggestion
export const encodeHtml = (str: string) => str.replace(/[<>]/g, tag => entities[tag] || tag);
```

File: src/htmlEntities.ts [hunk 3]
```diff
@@ -0,0 +1,6 @@
+const entities: { [key: string]: string } = {
+  '<': '&lt;',
+  '>': '&gt;',
+};
+
+export const encodeHtml = (str: string) => str.replace(/[<>]/g, tag => entities[tag] || tag);
```
Comment (samouss) [inline src/htmlEntities.ts]: We have already `marked` as dependency maybe we can rely on it to escape the HTML.

Comment (Haroenv) [reply src/htmlEntities.ts]: i don't think marked has html encoding? https://github.com/markedjs/marked/issues/1232
